# Workflow name, attached to the repo
name: Worflow 1
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
# Define when to trigger the worflow
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
on: workflow_dispatch
jobs:
  # Can be any name
  my-first-job:
    # Job runner
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-latest
    # Sequential steps, that will execute in the runner     
    steps:
      - name: Priting Hello
        run: echo "Hello!"
      - name: Printing Done
        run: echo "Done!"
      - run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
          echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
          ls ${{ github.workspace }}
          echo "ğŸ This job's status is ${{ job.status }}."
